// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `handle_message`, `process_buffer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `try_from`

Stream<bool> listenGetScreen() =>
    RustLib.instance.api.crateApiSimpleListenGetScreen();

Future<void> initialize({required int fd}) =>
    RustLib.instance.api.crateApiSimpleInitialize(fd: fd);

Stream<MessageToDart> initializeStreaming({required int fd}) =>
    RustLib.instance.api.crateApiSimpleInitializeStreaming(fd: fd);

@freezed
sealed class MessageToDart with _$MessageToDart {
  const MessageToDart._();

  const factory MessageToDart.getScreenInfo() = MessageToDart_GetScreenInfo;
  const factory MessageToDart.screenUpdate(Uint8List field0) =
      MessageToDart_ScreenUpdate;
}
